# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20170803_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
