# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sphboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_googleblogping', models.BooleanField(help_text=b'Enable ping to blogsearch.google.com ?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sphboard.Category', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Draft'), (2, b'Published'), (3, b'Hidden')])),
                ('slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sphboard.Post', unique=True)),
            ],
        ),
    ]
