# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategoryconfig',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sphboard.Category'),
        ),
        migrations.AlterField(
            model_name='blogpostextension',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sphboard.Post'),
        ),
    ]
